apiVersion: v1
kind: Service
metadata:
  name: portfolio-service-nodeport
  namespace: portfolio-louis
  labels:
    app: portfolio
spec:
  selector:
    app: portfolio
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
  type: NodePort